//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace custmodeldemo
{

    public partial class Customer_Info
    {
        public string Cust_Name { get; set; }
        public string Cust_Age { get; set; }
        public string Cust_id { get; set; }
        public string Cust_Email { get; set; }
        public string Cust_phone { get; set; }
    }
}
