//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCIOPRO_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBillingInfo
    {
        public int BillingId { get; set; }
        public string BillingEmail { get; set; }
        public long Phone { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public int CountryId { get; set; }
        public int StateId { get; set; }
        public string City { get; set; }
        public int ZipCode { get; set; }
    
        public virtual tblCountry tblCountry { get; set; }
        public virtual tblState tblState { get; set; }
    }
}
