//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCIOPRO_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCreditInfo
    {
        public int CreditId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CardNumber { get; set; }
        public string SecurityCode { get; set; }
        public string PromoCode { get; set; }
        public string ReferalCode { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public System.Guid TenantId { get; set; }
    }
}
