//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCIOPRO_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTenant
    {
        public int TId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public string CompanyName { get; set; }
        public string SubDomain { get; set; }
        public int PlanId { get; set; }
        public System.Guid TenantId { get; set; }
    
        public virtual tblPlan tblPlan { get; set; }
    }
}
