//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication14
{
    using System;
    using System.Collections.Generic;
    
    public partial class custom
    {
        public Nullable<short> Age { get; set; }
        public short ID { get; set; }
        public string Emp_Name { get; set; }
        public string Emp_email { get; set; }
    }
}
